### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by Mervfau** [sourcey/symple-client#3]
I get this when I try to run symple.webrtc.test.html
socket.io.min.js:2 GET https://localhost:4500/socket.io/1/?t=1427942848344 net::ERR_CONNECTION_REFUSED
I solved all of the link problems but I do not know socket.io 
Have a super one!
Merv

**Comment by auscaster** [comment]
Hi Merv
You will need to install and run the [symple node server](https://github.com/sourcey/symple-server-node) for the client to work. Have you done that already?
Cheers
Kam
