### ISSUE TITLE
Scalable broadcast webRTC stream

### ISSUE THREAD

**Issue by colinbouvry** [sourcey/symple-client#7]
Hello,
I use webrtcstreamer.exe and symple server with node.js in folder webrtc\samples\webrtcstreamer\client
It work very fine but with one client at the same time !
How to connect multiple webRTC browsers stream at the same time ?

Perhaps to use  RTCMultiConnection.js and TURN server !

![image](https://user-images.githubusercontent.com/985676/34458262-9a136946-edcb-11e7-9504-1b1287ca807e.png)

https://github.com/muaz-khan/WebRTC-Experiment/issues/2

Any idea ?

Thanks a lot
Colin

**Comment by auscaster** [comment]
You will need to setup a full ICE stack for this, and also modify the C++ code to handle STUN and TURN candidates.
