### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by YasharF** [sourcey/symple-client#8]
http://symple.sourcey.com doesn't seem to be in service anymore.

**Comment by sunapi386** [comment]
+1

**Comment by auscaster** [comment]
Site is back up guys. There is an issue on chrome since build 47 which you can solve with the workaround mentioned here: https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https/34198101

I'll look at adding https for the demo soon.
